spring:
  application:
    name: backend

  datasource:
    url: jdbc:postgresql://localhost:5433/devops_monitor
    username: postgres
    password: ${DB_PASSWORD}

  jpa:
    hibernate:
      ddl-auto: update

    show-sql: true

    properties:
      hibernate:
        format_sql: true

  flyway:
    enabled: false

server:
  port: 8080