spring:
  application:
    name: backend

  datasource:
    url: jdbc:postgresql://postgres:5432/devops_monitor
    username: postgres
    password: ${DB_PASSWORD}

  frontend:
    build:
      context: ./frontend
    container_name: devops-frontend
    ports:
      - "3000:3000"
    depends_on:
      - backend

  jpa:
    hibernate:
      ddl-auto: update

    show-sql: true

    properties:
      hibernate:
        format_sql: true

  flyway:
    enabled: false

server:
  port: 8080